version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    env_file: .env
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s"
    container_name: fargate-test_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
    volumes:
      - .:/app:cached
      - /app/log
      - /app/tmp
      - node_modules-volume:/app/node_modules
      - bundle-volume:/app/vendor
      - letter-opener-volume:/app/tmp/letter_opener
    # 直接railsアプリにアクセスする用のポートの設定
    ports:
      - 3000:3000
    # nginxコンテナからリンクされるとき用
    expose:
      - 3000
    links:
      - db
    tty: true
    stdin_open: true
    networks:
      - app-net

  db:
    image: mysql:5.7.30
    ports:
      - 3306:3306
    volumes:
      - fargate-test_db:/var/lib/mysql:delegated
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: fargate_test_development
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-net
    container_name: fargate-test_db

  nginx:
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile.nginx
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  fargate-test_db:
  bundle-volume:
    driver: local
  node_modules-volume:
    driver: local
  letter-opener-volume:
    driver: local

networks:
  app-net: